defaults:
  - default.yaml

neural_net_class_name: "PointNet"
neural_net_hparams:
  batch_norm: true
  MLP1_channels: ["${model.d_in}", 64, 64]
  MLP2_channels: [64, 256, 512, 1024]
  MLP3_channels: [1088, 512, 256, 64, 4]
  num_classes: "${model.num_classes}"

