_target_: lidar_multiclass.datamodules.datamodule.DataModule

prepared_data_dir: ${oc.env:PREPARED_DATA_DIR}

num_workers: 1
batch_size: 32
subsample_size: 12500
subtile_width_meters: 50

augment: false

# By default, do not use the test set unless explicitely required by user.
use_val_data_at_test_time: true

# Dataset Specific information
defaults:
  - dataset_description: SwissSURFACE3D_all_6_classes.yaml
