_convert_: all  # For omegaconf struct to be converted to python dictionnaries
# classification_preprocessing_dict = {source_class_code_int: target_class_code_int},
classification_preprocessing_dict: {2: 1, 3: 1, 9: 1, 17: 1}
# classification_dict = {code_int: name_str, ...} and MUST be sorted (increasing order).
classification_dict: {1: "unclassified", 6: "building"}

# Input and output dims of neural net are dataset dependant:
d_in: 10
num_classes: 2

# loading functions for data object prepared via lidar_multiclass/datamodule/data.py
load_las_func:
  _target_: functools.partial
  _args_:
    - "${get_method:lidar_multiclass.datamodules.data.SwissTopoLidarDataLogic.load_las}"